# Generated by Django 2.1.2 on 2018-10-20 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogpost',
            old_name='description',
            new_name='content',
        ),
    ]
